"""Known column schemas for supported Sentinel log tables — full port of
lib/validation/schemas.ts. Extracted from the validated context assets;
used by validate_kql to flag hallucinated or incorrect column references.
"""

TABLE_SCHEMAS: dict[str, list[str]] = {
    "AzureActivity": [
        "TimeGenerated",
        "OperationNameValue",
        "OperationName",
        "ActivityStatusValue",
        "Caller",
        "CallerIpAddress",
        "ResourceId",
        "ResourceGroup",
        "SubscriptionId",
        "Properties",
        "Authorization",
        "Claims",
        "CorrelationId",
        "Level",
        "Type",
        "_ResourceId",
    ],
    # The four Azure Storage data-plane tables (blob/file/queue/table) share one
    # schema — same columns, differing only in OperationName vocabulary.
    "StorageBlobLogs": [
        "TimeGenerated",
        "OperationName",
        "StatusCode",
        "StatusText",
        "AuthenticationType",
        "CallerIpAddress",
        "Uri",
        "ObjectKey",
        "UserAgentHeader",
        "AccountName",
        "ResponseBodySize",
        "RequesterObjectId",
        "RequesterUpn",
        "RequesterAppId",
        "CorrelationId",
        "Type",
        "_ResourceId",
    ],
    "StorageFileLogs": [
        "TimeGenerated",
        "OperationName",
        "StatusCode",
        "StatusText",
        "AuthenticationType",
        "CallerIpAddress",
        "Uri",
        "ObjectKey",
        "UserAgentHeader",
        "AccountName",
        "ResponseBodySize",
        "RequesterObjectId",
        "RequesterUpn",
        "RequesterAppId",
        "CorrelationId",
        "Type",
        "_ResourceId",
    ],
    "StorageQueueLogs": [
        "TimeGenerated",
        "OperationName",
        "StatusCode",
        "StatusText",
        "AuthenticationType",
        "CallerIpAddress",
        "Uri",
        "ObjectKey",
        "UserAgentHeader",
        "AccountName",
        "ResponseBodySize",
        "RequesterObjectId",
        "RequesterUpn",
        "RequesterAppId",
        "CorrelationId",
        "Type",
        "_ResourceId",
    ],
    "StorageTableLogs": [
        "TimeGenerated",
        "OperationName",
        "StatusCode",
        "StatusText",
        "AuthenticationType",
        "CallerIpAddress",
        "Uri",
        "ObjectKey",
        "UserAgentHeader",
        "AccountName",
        "ResponseBodySize",
        "RequesterObjectId",
        "RequesterUpn",
        "RequesterAppId",
        "CorrelationId",
        "Type",
        "_ResourceId",
    ],
    # The DEDICATED Key Vault table. These are its real columns, per the Azure
    # Monitor table reference and confirmed against a live workspace's
    # `getschema`. What was here before -- identity_s, id_s, httpStatusCode_d,
    # CallerIPAddress -- is the AzureDiagnostics spelling of the same data, and
    # listing it meant validate_kql PASSED queries the workspace then refused
    # with "Failed to resolve scalar expression". Key Vault logs only get those
    # names when they land in the shared AzureDiagnostics table.
    "AZKVAuditLogs": [
        "TimeGenerated",
        "OperationName",
        "OperationVersion",
        "ResultType",
        "ResultSignature",
        "ResultDescription",
        "HttpStatusCode",
        "CallerIpAddress",
        "Identity",
        "Id",
        "RequestUri",
        "ClientInfo",
        "CorrelationId",
        "DurationMs",
        "IsRbacAuthorized",
        "IsAccessPolicyMatch",
        "IsAddressAuthorized",
        "AddressAuthorizationType",
        "AppliedAssignmentId",
        "TrustedService",
        "SubnetId",
        "Tlsversion",
        "Algorithm",
        "Properties",
        "KeyProperties",
        "SecretProperties",
        "CertificateProperties",
        "CertificatePolicyProperties",
        "CertificateIssuerProperties",
        "CertificateRequestProperties",
        "StorageAccountProperties",
        "StorageSasDefinitionProperties",
        "VaultProperties",
        "NetworkAcls",
        "Nsp",
        "Sku",
        "EnabledForDeployment",
        "EnabledForDiskEncryption",
        "EnabledForTemplateDeployment",
        "EnableSoftDelete",
        "EnableRbacAuthorization",
        "EnablePurgeProtection",
        "SoftDeleteRetentionInDays",
        "HsmPoolResourceId",
        "SourceSystem",
        "TenantId",
        "Type",
        "_ResourceId",
    ],
    # Azure Functions host/execution telemetry (microsoft.web/sites). NOT an
    # access-audit table: no OperationName / CallerIpAddress / StatusCode here.
    "FunctionAppLogs": [
        "TimeGenerated",
        "Category",
        "Level",
        "LevelId",
        "Message",
        "FunctionName",
        "FunctionInvocationId",
        "HostInstanceId",
        "HostVersion",
        "ProcessId",
        "EventId",
        "EventName",
        "ActivityId",
        "ExceptionType",
        "ExceptionMessage",
        "ExceptionDetails",
        "RoleInstance",
        "AppName",
        "Location",
        "Type",
        "_ResourceId",
    ],
    # App Service publishing-logon audit (microsoft.web/sites). Successful
    # publishing logons only — no result/status column. Source IP is UserAddress.
    "AppServiceAuditLogs": [
        "TimeGenerated",
        "OperationName",
        "Protocol",
        "User",
        "UserAddress",
        "UserDisplayName",
        "Category",
        "Type",
        "_ResourceId",
    ],
    # Azure Firewall structured logs (microsoft.network/azurefirewalls). Network
    # security telemetry — each table logs data-plane packets matched by a rule/
    # signature. SourcePort/DestinationPort/Severity are INT; Action is a string.
    # Table-specific absences below are deliberate (they prevent hallucination).
    "AZFWNetworkRule": [
        "TimeGenerated", "Protocol", "SourceIp", "SourcePort", "DestinationIp",
        "DestinationPort", "Action", "ActionReason", "Policy", "RuleCollection",
        "RuleCollectionGroup", "Rule", "Type", "_ResourceId",
    ],
    # Application rule: FQDN/URL based — NO DestinationIp column.
    "AZFWApplicationRule": [
        "TimeGenerated", "Protocol", "SourceIp", "SourcePort", "DestinationPort",
        "Fqdn", "TargetUrl", "WebCategory", "Action", "ActionReason", "Policy",
        "RuleCollection", "RuleCollectionGroup", "Rule", "IsTlsInspected",
        "IsExplicitProxyRequest", "Type", "_ResourceId",
    ],
    # DNAT translation — NO Action column.
    "AZFWNatRule": [
        "TimeGenerated", "Protocol", "SourceIp", "SourcePort", "DestinationIp",
        "DestinationPort", "TranslatedIp", "TranslatedPort", "Policy",
        "RuleCollection", "RuleCollectionGroup", "Rule", "Type", "_ResourceId",
    ],
    # DNS proxy events — NO Action, NO DestinationIp.
    "AZFWDnsQuery": [
        "TimeGenerated", "Protocol", "SourceIp", "SourcePort", "QueryId",
        "QueryType", "QueryClass", "QueryName", "RequestSize", "DnssecOkBit",
        "EDNS0BufferSize", "ResponseCode", "ResponseFlags", "ResponseSize",
        "RequestDurationSecs", "ErrorNumber", "ErrorMessage", "Type", "_ResourceId",
    ],
    "AZFWThreatIntel": [
        "TimeGenerated", "Protocol", "SourceIp", "SourcePort", "DestinationIp",
        "DestinationPort", "Fqdn", "TargetUrl", "ThreatDescription", "Action",
        "IsTlsInspected", "Type", "_ResourceId",
    ],
    "AZFWIdpsSignature": [
        "TimeGenerated", "Protocol", "SourceIp", "SourcePort", "DestinationIp",
        "DestinationPort", "Action", "Category", "Description", "Severity",
        "SignatureId", "Type", "_ResourceId",
    ],
    # Azure Container Registry audit logs (microsoft.containerregistry/registries).
    # Supply-chain: who authenticated to and pushed/pulled images. DurationMs is a
    # STRING (not int); CallerIpAddress is lowercase-p; Identity is the principal.
    "ContainerRegistryLoginEvents": [
        "TimeGenerated", "OperationName", "Identity", "LoginServer",
        "CallerIpAddress", "UserAgent", "Region", "ResultType", "ResultDescription",
        "DurationMs", "CorrelationId", "JwtId", "Category", "Type", "_ResourceId",
    ],
    "ContainerRegistryRepositoryEvents": [
        "TimeGenerated", "OperationName", "Repository", "Tag", "Digest", "Identity",
        "LoginServer", "CallerIpAddress", "UserAgent", "MediaType", "ArtifactType",
        "Size", "Region", "ResultType", "ResultDescription", "DurationMs",
        "CorrelationId", "Category", "UserTenantId", "Type", "_ResourceId",
    ],
    # Azure Backup (microsoft.recoveryservices/vaults). Ransomware anti-recovery:
    # stop-protection-with-delete-data, modify-policy, restore. ExtendedProperties
    # is DYNAMIC. The acting principal is in AzureActivity (correlate for "who").
    "AzureBackupOperations": [
        "TimeGenerated", "OperationName", "OperationType", "OperationStartTime",
        "BackupManagementType", "Category", "ExtendedProperties", "SchemaVersion",
        "Type", "_ResourceId",
    ],
    "CoreAzureBackup": [
        "TimeGenerated", "OperationName", "BackupItemFriendlyName", "BackupItemName",
        "BackupItemType", "BackupItemUniqueId", "BackupItemProtectionState",
        "ProtectedContainerFriendlyName", "ProtectedContainerProtectionState",
        "SecondaryBackupProtectionState", "State", "PolicyName", "DatasourceType",
        "LatestRecoveryPointTime", "OldestRecoveryPointTime", "StorageConsumedInMBs",
        "VaultName", "VaultType", "ResourceGroupName", "SubscriptionId",
        "ExtendedProperties", "Type", "_ResourceId",
    ],
    "AddonAzureBackupJobs": [
        "TimeGenerated", "OperationName", "JobOperation", "JobOperationSubType",
        "JobStatus", "JobFailureCode", "JobUniqueId", "JobStartDateTime",
        "JobDurationInSecs", "AdHocOrScheduledJob", "BackupItemFriendlyName",
        "BackupItemUniqueId", "DataTransferredInMB", "RecoveryJobDestination",
        "RecoveryLocationType", "BackupManagementType", "VaultName",
        "ResourceGroupName", "ExtendedProperties", "Type", "_ResourceId",
    ],
    "AuditLogs": [
        "TimeGenerated",
        "OperationName",
        "Category",
        "Result",
        "InitiatedBy",
        "TargetResources",
        "CorrelationId",
        "Identity",
        "LoggedByService",
        "ResultReason",
        "AdditionalDetails",
        "Type",
        "_ResourceId",
    ],
    # AKSAudit and AKSAuditAdmin share an identical schema; AKSAuditAdmin
    # simply omits get/list events (enforced separately in validate_kql).
    "AKSAudit": [
        "TimeGenerated", "Verb", "ObjectRef", "User", "RequestUri",
        "ResponseStatus", "RequestObject", "ResponseObject", "SourceIps",
        "UserAgent", "Level", "Stage", "AuditId", "PodName", "Annotations",
        "RequestReceivedTime", "StageReceivedTime", "SourceSystem", "Type",
        "TenantId", "_ResourceId", "_SubscriptionId",
    ],
    "AKSAuditAdmin": [
        "TimeGenerated", "Verb", "ObjectRef", "User", "RequestUri",
        "ResponseStatus", "RequestObject", "ResponseObject", "SourceIps",
        "UserAgent", "Level", "Stage", "AuditId", "PodName", "Annotations",
        "RequestReceivedTime", "StageReceivedTime", "SourceSystem", "Type",
        "TenantId", "_ResourceId", "_SubscriptionId",
    ],
    "MicrosoftGraphActivityLogs": [
        "TimeGenerated",
        "AppId",
        "ServicePrincipalId",
        "UserId",
        "RequestUri",
        "RequestMethod",
        "ResponseStatusCode",
        "Scopes",
        "Roles",
        "ClientAuthMethod",
        "IPAddress",
        "UserAgent",
        "DurationMs",
        "ResponseSizeBytes",
        "SessionId",
        "UniqueTokenId",
        "TokenIssuedAt",
        "AadTenantId",
        "ApiVersion",
        "Type",
        "_ResourceId",
    ],
    # Microsoft 365 Unified Audit Log (Office 365 connector -> OfficeActivity).
    # Wide, flat table; security-relevant subset of the ~145 documented columns.
    "OfficeActivity": [
        "TimeGenerated", "Operation", "RecordType", "OfficeWorkload", "UserId",
        "UserType", "UserKey", "UserDomain", "ClientIP", "ResultStatus",
        "OfficeObjectId", "OfficeId", "Parameters", "Item", "MailboxOwnerUPN",
        "Logon_Type", "SourceFileName", "SourceRelativeUrl",
        "TargetUserOrGroupName", "Members", "ModifiedProperties", "SharingType",
        "OrganizationId", "Type", "_ResourceId",
    ],
    # Entra ID sign-in tables. ResultType is a STRING code ("0" == success).
    "SigninLogs": [
        "TimeGenerated", "Id", "CorrelationId", "UserPrincipalName", "UserId",
        "UserDisplayName", "AppDisplayName", "AppId", "ResourceDisplayName",
        "ResourceId", "IPAddress", "LocationDetails", "AutonomousSystemNumber",
        "ClientAppUsed", "UserAgent", "DeviceDetail", "AuthenticationRequirement",
        "ResultType", "ResultDescription", "Status", "ConditionalAccessStatus",
        "MfaDetail", "AuthenticationDetails", "RiskLevelDuringSignIn", "RiskState",
        "RiskDetail", "Type", "_ResourceId",
    ],
    "AADNonInteractiveUserSignInLogs": [
        "TimeGenerated", "Id", "CorrelationId", "UserPrincipalName", "UserId",
        "UserDisplayName", "AppDisplayName", "AppId", "ResourceDisplayName", "IPAddress", "LocationDetails", "ClientAppUsed", "UserAgent",
        "DeviceDetail", "ResultType", "ResultDescription", "Status",
        "ConditionalAccessStatus", "RiskLevelDuringSignIn", "RiskState",
        "Type", "_ResourceId",
    ],
    "AADServicePrincipalSignInLogs": [
        "TimeGenerated", "Id", "CorrelationId", "ServicePrincipalId",
        "ServicePrincipalName", "AppId", "ResourceDisplayName",
        "ResourceIdentity", "IPAddress", "Location", "ServicePrincipalCredentialKeyId",
        "ResultType", "ResultDescription", "ConditionalAccessStatus",
        "Type", "_ResourceId",
    ],
    "AADManagedIdentitySignInLogs": [
        "TimeGenerated", "Id", "CorrelationId", "ServicePrincipalId",
        "ServicePrincipalName", "ResourceDisplayName",
        "ResourceIdentity", "IPAddress", "Location", "ResultType",
        "ResultDescription", "Type", "_ResourceId",
    ],
    # Defender for Endpoint advanced-hunting Device* tables. TIME COLUMN IS
    # Timestamp (not TimeGenerated). Common backbone + table-specific columns.
    "DeviceProcessEvents": [
        "Timestamp", "DeviceId", "DeviceName", "ActionType", "ReportId",
        "FileName", "FolderPath", "ProcessCommandLine", "ProcessId", "SHA256",
        "SHA1", "MD5", "ProcessIntegrityLevel", "ProcessTokenElevation",
        "AccountName", "AccountDomain", "AccountSid",
        "InitiatingProcessFileName", "InitiatingProcessCommandLine",
        "InitiatingProcessId", "InitiatingProcessAccountName",
        "InitiatingProcessAccountDomain", "InitiatingProcessParentFileName",
        "InitiatingProcessSHA256", "AdditionalFields",
    ],
    "DeviceNetworkEvents": [
        "Timestamp", "DeviceId", "DeviceName", "ActionType", "ReportId",
        "RemoteIP", "RemoteUrl", "RemotePort", "RemoteIPType", "LocalIP",
        "LocalPort", "LocalIPType", "Protocol",
        "InitiatingProcessFileName", "InitiatingProcessCommandLine",
        "InitiatingProcessId", "InitiatingProcessAccountName",
        "InitiatingProcessSHA256", "AdditionalFields",
    ],
    "DeviceFileEvents": [
        "Timestamp", "DeviceId", "DeviceName", "ActionType", "ReportId",
        "FileName", "FolderPath", "SHA256", "SHA1", "MD5", "FileSize",
        "PreviousFileName", "PreviousFolderPath", "RequestAccountName",
        "RequestAccountDomain", "InitiatingProcessFileName",
        "InitiatingProcessCommandLine", "InitiatingProcessId",
        "InitiatingProcessAccountName", "InitiatingProcessSHA256", "AdditionalFields",
    ],
    "DeviceLogonEvents": [
        "Timestamp", "DeviceId", "DeviceName", "ActionType", "ReportId",
        "LogonType", "AccountName", "AccountDomain", "AccountSid", "IsLocalAdmin",
        "Protocol", "RemoteIP", "RemoteIPType", "RemoteDeviceName",
        "InitiatingProcessFileName", "InitiatingProcessAccountName",
        "InitiatingProcessId", "AdditionalFields",
    ],
    "DeviceRegistryEvents": [
        "Timestamp", "DeviceId", "DeviceName", "ActionType", "ReportId",
        "RegistryKey", "RegistryValueName", "RegistryValueType", "RegistryValueData",
        "PreviousRegistryKey", "PreviousRegistryValueName", "PreviousRegistryValueData",
        "InitiatingProcessFileName", "InitiatingProcessCommandLine",
        "InitiatingProcessId", "InitiatingProcessAccountName",
        "InitiatingProcessSHA256",
    ],
    # Legacy Azure AD Graph (graph.windows.net) API activity. ResponseStatusCode
    # is an INT. Flat, one row per request.
    "AADGraphActivityLogs": [
        "TimeGenerated", "RequestId", "RequestUri", "RequestMethod",
        "ResponseStatusCode", "ResultSignature", "UserId", "AppId",
        "ServicePrincipalId", "ActorType", "CallerIpAddress", "UserAgent",
        "SessionId", "DeviceId", "DurationMs", "ResponseSizeBytes", "ApiVersion",
        "ClientAuthMethod", "IdentityProvider", "Roles", "Scopes", "Wids",
        "Location", "Type", "_ResourceId",
    ],
}

# Flat tables should never use mv-expand.
FLAT_TABLES: set[str] = {
    "AzureActivity",
    "MicrosoftGraphActivityLogs",
    "AADGraphActivityLogs",
    "StorageBlobLogs",
    "StorageFileLogs",
    "StorageQueueLogs",
    "StorageTableLogs",
    "AZKVAuditLogs",
    "FunctionAppLogs",
    "AppServiceAuditLogs",
    "AZFWNetworkRule",
    "AZFWApplicationRule",
    "AZFWNatRule",
    "AZFWDnsQuery",
    "AZFWThreatIntel",
    "AZFWIdpsSignature",
    "ContainerRegistryLoginEvents",
    "ContainerRegistryRepositoryEvents",
    "AzureBackupOperations",
    "CoreAzureBackup",
    "AddonAzureBackupJobs",
    "OfficeActivity",
}

# Fields that are plain strings and should NOT be wrapped in tostring().
PLAIN_STRING_FIELDS: dict[str, set[str]] = {
    "AzureActivity": {"Caller", "CallerIpAddress"},
    # blob/file/queue/table share the storage schema — same plain-string fields.
    **{
        t: {
            "CallerIpAddress",
            "OperationName",
            "StatusCode",
            "StatusText",
            "AuthenticationType",
            "Uri",
            "ObjectKey",
            "UserAgentHeader",
            "AccountName",
            "RequesterUpn",
            "RequesterObjectId",
            "RequesterAppId",
        }
        for t in ("StorageBlobLogs", "StorageFileLogs", "StorageQueueLogs", "StorageTableLogs")
    },
    "MicrosoftGraphActivityLogs": {
        "AppId",
        "ServicePrincipalId",
        "UserId",
        "RequestUri",
        "RequestMethod",
        "IPAddress",
        "UserAgent",
        "Scopes",
        "Roles",
        "SessionId",
        "UniqueTokenId",
        "AadTenantId",
        "ApiVersion",
    },
    "AADGraphActivityLogs": {
        "RequestUri",
        "RequestMethod",
        "ResultSignature",
        "UserId",
        "AppId",
        "ServicePrincipalId",
        "ActorType",
        "CallerIpAddress",
        "UserAgent",
        "SessionId",
        "ApiVersion",
    },
    "SigninLogs": {
        "UserPrincipalName",
        "UserId",
        "AppDisplayName",
        "AppId",
        "IPAddress",
        "ResultType",
        "ClientAppUsed",
        "UserAgent",
    },
    "AADNonInteractiveUserSignInLogs": {
        "UserPrincipalName",
        "UserId",
        "AppDisplayName",
        "IPAddress",
        "ResultType",
        "ClientAppUsed",
    },
    "AADServicePrincipalSignInLogs": {
        "ServicePrincipalId",
        "ServicePrincipalName",
        "AppId",
        "IPAddress",
        "ResultType",
    },
    "AADManagedIdentitySignInLogs": {
        "ServicePrincipalId",
        "ServicePrincipalName",
        "IPAddress",
        "ResultType",
    },
    # Defender Device* tables — common plain-string fields (per-table extras exist
    # but these cover the shared backbone the model most often over-wraps).
    "DeviceProcessEvents": {
        "DeviceName", "ActionType", "FileName", "FolderPath", "ProcessCommandLine",
        "SHA256", "AccountName", "InitiatingProcessFileName",
        "InitiatingProcessCommandLine", "InitiatingProcessAccountName",
        "InitiatingProcessParentFileName",
    },
    "DeviceNetworkEvents": {
        "DeviceName", "ActionType", "RemoteIP", "RemoteUrl", "Protocol",
        "InitiatingProcessFileName", "InitiatingProcessCommandLine",
        "InitiatingProcessAccountName",
    },
    "DeviceFileEvents": {
        "DeviceName", "ActionType", "FileName", "FolderPath", "SHA256",
        "InitiatingProcessFileName", "InitiatingProcessCommandLine",
        "InitiatingProcessAccountName",
    },
    "DeviceLogonEvents": {
        "DeviceName", "ActionType", "LogonType", "AccountName", "AccountDomain",
        "RemoteIP", "InitiatingProcessFileName", "InitiatingProcessAccountName",
    },
    "DeviceRegistryEvents": {
        "DeviceName", "ActionType", "RegistryKey", "RegistryValueName",
        "RegistryValueData", "InitiatingProcessFileName",
        "InitiatingProcessCommandLine", "InitiatingProcessAccountName",
    },
}
